---
title: "Dotplot with PBMC3K example dataset"
author: "Simon Leonard"
date: "22/02/01"
output:
  html_document:
    toc: yes
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{FlexDotPlot_PBMC3K_dataset}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

Usefull links :
https://github.com/satijalab/seurat-data
https://satijalab.org/seurat/v3.2/visualization_vignette.html

## Libraries

```{r warning=F, message=F}
library(Seurat)
library(SeuratData) # to install -> devtools::install_github('satijalab/seurat-data')

```


## Get PBMC data via SeuratData package

```{r warning=F, message=F}
InstallData("pbmc3k")
data("pbmc3k")
pbmc3k
```

## Dot plot with Seurat package 
```{r}
features <- c("LYZ", "CCL5", "IL32", "PTPRCAP", "FCGR3A", "PF4")

# Dot plots - the size of the dot corresponds to the percentage of cells expressing the feature
# in each cluster. The color represents the average expression level
dp=DotPlot(pbmc3k.final, features = features) + RotatedAxis()

dp
```



## Dot plot with FlexDotPlot package
```{r message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
library(FlexDotPlot)

# Seurat-like dot plot with FlexDotPlot
dot_plot(dp$data[,c(3,4,1,2,5)], size_var = "pct.exp", col_var = "avg.exp.scaled", 
         size_legend = "Percent Expressed", col_legend = "Average Expression",
         x.lab.pos = "bottom", display_max_sizes = FALSE)

# Dot plot with shape type (and not size) controlled by "Percent Expressed" parameter 
dot_plot(dp$data[,c(3,4,1,2,5)], shape_var = "pct.exp", col_var = "avg.exp.scaled", 
         shape_legend = "Percent Expressed", col_legend = "Average Expression", x.lab.pos = "bottom")

# Add dendrograms
dotplot=dot_plot(dp$data[,c(3,4,1,2,5)], shape_var = "pct.exp", col_var = "avg.exp.scaled", 
         shape_legend = "Percent Expressed", col_legend = "Average Expression", x.lab.pos = "bottom", 
         dend_x_var = c("pct.exp","avg.exp.scaled"), dend_y_var = c("pct.exp","avg.exp.scaled"), hclust_method = "ward.D2", do.return=T)
```

## Dot plot with with Seurat and same gene/cluster ordering
```{r message=FALSE, warning=FALSE, fig.width=8, fig.height=6}
Idents(pbmc3k.final)=factor(Idents(pbmc3k.final), levels=dotplot$plot$grobs[[4]]$label)
DotPlot(pbmc3k.final, features = dotplot$plot$grobs[[10]]$label) + RotatedAxis()

```


## Session Info
```{r}
sessionInfo()
```

