---
title: "Dotplot with PBMC3K example dataset"
author: "Simon Leonard"
date: "22/02/01"
output:
  html_document:
    toc: yes
    toc_depth: 3
vignette: >
  %\VignetteIndexEntry{FlexDotPlot_CBMC_dataset}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

Usefull links :
https://github.com/satijalab/seurat-data
https://satijalab.org/seurat/v3.2/visualization_vignette.html

## Libraries

```{r warning=F, message=F}
library(Seurat)
library(ggplot2)
library(plyr)
require(SeuratData)
```


## Get CBMC data
Inspired from cbmc.SeuratData package - https://github.com/satijalab/seurat-data

```{r warning=F, message=F}
InstallData("cbmc")
data("cbmc")
cbmc
```

## Filter Data 
```{r warning=F, message=F}
Idents(cbmc)="rna_annotations"
cbmc=subset(cbmc, idents=c("Eryth", "Mouse","Multiplets","T/Mono doublets"), invert=T)

cbmc <- NormalizeData(cbmc, assay = "ADT", normalization.method = "CLR")
cbmc <- ScaleData(cbmc, assay = "ADT")

rownames(cbmc@assays$ADT@data)=revalue(rownames(cbmc@assays$ADT@data), c(CD3="CD3E", CD8="CD8A", CD45RA="PTPRC", CD56="NCAM1", 
                                                                         CD16="FCGR3A", CD11c="ITGAX"))
```


## Get Seurat DotPlot data
```{r message=FALSE, warning=FALSE, fig.width=8}
selected_features=rownames(cbmc@assays$ADT@data)

dotplot_adt=DotPlot(cbmc, assay = "ADT", features = selected_features) + ggtitle("Antibody_expression")
dotplot_rna=DotPlot(cbmc, assay = "RNA", features = selected_features) + ggtitle("RNA_expression")
```



## Set antibodies expression cutoff  + calculate percentage of cells with adt expression above cutoff

```{r message=FALSE, warning=FALSE}
for (i in selected_features){
  print(VlnPlot(cbmc, assay ="ADT", features = i, pt.size = 0, group.by = "orig.ident") + scale_y_continuous(breaks = seq(0,4,0.25)))
}

cutoffs=data.frame(adt=selected_features, cutoff=c(1,1,1,0.5,1,1,1,0.5,1.25,1.25))

dotplot_adt$data$pct.exp.sup.cutoff=NA
for (i in 1:nrow(dotplot_adt$data)){
  cutoff=cutoffs$cutoff[cutoffs$adt==as.character(dotplot_adt$data$features.plot[i])]
  dotplot_adt$data$pct.exp.sup.cutoff[i]=(sum(cbmc@assays$ADT@data[as.character(dotplot_adt$data$features.plot[i]),WhichCells(cbmc, idents=as.character(dotplot_adt$data$id[i]))] > cutoff))/(sum(Idents(cbmc)==as.character(dotplot_adt$data$id[i])))*100
}
# summary(dotplot_adt$data)
```


## Merge ADT and RNAdotplot data

```{r}
data_to_plot=dotplot_rna$data
identical(data_to_plot$features.plot, dotplot_adt$data$features.plot)
identical(data_to_plot$id, dotplot_adt$data$id)

colnames(data_to_plot)[!colnames(data_to_plot) %in% c("features.plot", "id")]=paste("RNA",colnames(data_to_plot)[!colnames(data_to_plot) %in% c("features.plot", "id")], sep=".")
colnames(dotplot_adt$data)[!colnames(dotplot_adt$data) %in% c("features.plot", "id")]=paste("ADT",colnames(dotplot_adt$data)[!colnames(dotplot_adt$data) %in% c("features.plot", "id")], sep=".")

data_to_plot=cbind(data_to_plot, dotplot_adt$data[,which(!colnames(dotplot_adt$data) %in% c("id", "features.plot"))])
data_to_plot=data_to_plot[,c(which(colnames(data_to_plot) %in% c("id", "features.plot")), which(!colnames(data_to_plot) %in% c("id", "features.plot")))]

data_to_plot$RNA.avg.exp.log2p1=log2(data_to_plot$RNA.avg.exp+1)
data_to_plot$ADT.avg.exp.log2p1=log2(data_to_plot$ADT.avg.exp+1)

colnames(data_to_plot)[colnames(data_to_plot)=="ADT.pct.exp"]="ADT.pct.exp.sup.0"
data_to_plot$features.plot=revalue(data_to_plot$features.plot, c(PTPRC="PTPRC_CD45RA", NCAM1="NCAM1_CD56", FCGR3A="FCGR3A_CD16", ITGAX="ITGAX_CD11c"))
data_to_plot=data_to_plot[,c(1,2,4,3,10,5,7,9,6,11,8)]

data_to_plot[,3:ncol(data_to_plot)]=round(data_to_plot[,3:ncol(data_to_plot)], 2)
data_to_plot[,grep("pct.exp", colnames(data_to_plot))]=round(data_to_plot[,grep("pct.exp", colnames(data_to_plot))])
```



## Change cell type/gene names

```{r}
data_to_plot$id=revalue(data_to_plot$id, c(NK = "Natural killer lymphocytes", "CD14+ Mono"= "CD14+ Monocytes", "Mk"="Megakaryocytes", 
                                           "CD34+"="CD34+ cells", DC="Dendritic cells","Memory CD4 T"="Memory CD4+ T lymphocytes", "CD8 T"="CD8+ T lymphocytes",
                                           "CD16+ Mono"="CD16+ Monocytes", B="B lymphocytes", pDCs="Plasmacytoid Dendritic cells", "Naive CD4 T"="Naive CD4+ T lymphocytes"))

data_to_plot$features.plot=revalue(data_to_plot$features.plot, c(NCAM1_CD56="NCAM1 (CD56)", ITGAX_CD11c="ITGAX (CD11c)", 
                                                                 FCGR3A_CD16="FCGR3A (CD16)", PTPRC_CD45RA="PTPRC (CD45RA)",
                                                                 CCR5="CCR5 (CD195)", CCR7="CCR7 (CD197)"))
```


## Label canonical markers 

```{r}
data_to_plot$canonical_marker="no"
data_to_plot$canonical_marker[(data_to_plot$id=="CD14+ Monocytes" & data_to_plot$features.plot=="CD14")|
                                (data_to_plot$id=="CD16+ Monocytes" & data_to_plot$features.plot=="FCGR3A (CD16)")|
                                (data_to_plot$id %in% c("CD14+ Monocytes", "CD16+ Monocytes", "Dendritic cells") & 
                                   data_to_plot$features.plot=="ITGAX (CD11c)")|
                                (data_to_plot$id=="Natural killer lymphocytes" & data_to_plot$features.plot=="NCAM1 (CD56)")|
                                (data_to_plot$id=="CD34+ cells" & data_to_plot$features.plot=="CD34")|
                                (data_to_plot$id=="B lymphocytes" & data_to_plot$features.plot=="CD19")|
                                (data_to_plot$id %in% c("Naive CD4+ T lymphocytes", "Memory CD4+ T lymphocytes") & 
                                   data_to_plot$features.plot=="CD4")|
                                (data_to_plot$id=="CD8+ T lymphocytes" & data_to_plot$features.plot=="CD8A")|
                                (data_to_plot$id %in% c("Naive CD4+ T lymphocytes", "Memory CD4+ T lymphocytes", "CD8+ T lymphocytes") & 
                                   data_to_plot$features.plot=="CD3E")]="yes"
```


## Perform dotplot visualization

```{r message=F, warning=F, fig.width=12}
library(FlexDotPlot)

dotplot = dot_plot( 
  data.to.plot=data_to_plot[,c("features.plot","id", colnames(data_to_plot)[!(colnames(data_to_plot) %in% c("features.plot","id"))])], 
  size_var="RNA.avg.exp.scaled",col_var="ADT.avg.exp.scaled", text_var="ADT.pct.exp.sup.cutoff",
  shape_var="canonical_marker", shape_use = c("\u25CF","\u2737"),
  x.lab.pos="bottom",y.lab.pos="left", 
  cols.use=c("lightgrey","orange","red", "darkred"),size_legend="RNA", col_legend="ADT", shape_legend="Canonical marker ?", 
  shape.scale =12, text.size=3, 
  plot.legend = TRUE,x.lab.rot = TRUE, 
  size.breaks.number=4, color.breaks.number=4, shape.breaks.number=5
  , dend_x_var=c("RNA.avg.exp.scaled","ADT.avg.exp.scaled"), dend_y_var=c("RNA.avg.exp.scaled","ADT.avg.exp.scaled"), dist_method="euclidean", hclust_method="ward.D", do.return = TRUE)

dotplot = dot_plot( 
  data.to.plot=data_to_plot[,c("features.plot","id", colnames(data_to_plot)[!(colnames(data_to_plot) %in% c("features.plot","id"))])], 
  size_var="ADT.pct.exp.sup.cutoff",col_var="ADT.avg.exp.scaled", text_var="RNA.pct.exp",
  shape_var="canonical_marker", shape_use = c("\u25CF","\u2737"),
  x.lab.pos="bottom",y.lab.pos="left", 
  cols.use=c("lightgrey","orange","red", "darkred"),size_legend="ADT.pct", col_legend="ADT.exp", shape_legend="Canonical marker ?", 
  shape.scale =12, text.size=3, 
  plot.legend = TRUE,x.lab.rot = TRUE, 
  size.breaks.number=5, color.breaks.number=4, shape.breaks.number=5
  , dend_x_var=c("RNA.avg.exp.scaled","ADT.avg.exp.scaled"), dend_y_var=c("RNA.avg.exp.scaled","ADT.avg.exp.scaled"), dist_method="euclidean", hclust_method="ward.D", do.return = TRUE)
```


## Session Info
```{r}
sessionInfo()
```








